version: '2'

services:

### Applications Code Container #############################
    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www

### Nginx Server Container ##################################
    nginx:
      build:
        context: ./nginx
      volumes_from:
        - applications
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### Workspace Utilities Container ###########################
    workspace:
      build:
        context: ./workspace
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php-fpm
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - backend

### MySQL Container #########################################
    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

### Redis Container #########################################
    redis:
      build: ./redis
      ports:
        - "6379:6379"
      networks:
        - backend

### ElasticSearch Container #################################
    elasticsearch:
      build: ./elasticsearch
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
#      depends_on:
#        - php-fpm
      networks:
        - frontend
        - backend

### Networks Setup ############################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
