version: '2'

services:

### Applications Code Container #############################


### MySQL Container #########################################
    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

### Redis Container #########################################
    redis:
      build: ./redis
      ports:
        - "6379:6379"
      networks:
        - backend

### ElasticSearch Container #################################
    elasticsearch:
      build: ./elasticsearch
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
#      depends_on:
#        - php-fpm
      networks:
        - frontend
        - backend

### Networks Setup ############################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
