version: '2'

services:

### Applications Code Container #############################

### Redis Container #########################################
    redis:
      build: ./redis
      ports:
        - "6379:6379"
      networks:
        - backend

### ElasticSearch Container #################################
    elasticsearch:
      build: ./elasticsearch
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
#      depends_on:
#        - php-fpm
      networks:
        - frontend
        - backend

### Networks Setup ############################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
