version: '3.5'

services:

  ### Applications Code Container #############################
  applications:
    restart: unless-stopped
    image: tianon/true
    volumes:
      - ${APPLICATION}:/var/www

  ### Nginx Server Container ##################################
  nginx:
    #image: laradocklite/nginx:latest
    build:
      context: ./nginx
    restart: unless-stopped
    volumes_from:
      - applications
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### Workspace Utilities Container ###########################
  workspace:
    #image: laradocklite/workspace:latest
    build:
      context: ./workspace
    restart: unless-stopped
    volumes_from:
      - applications
    volumes:
      - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./workspace/config.php:/root/.config/psysh/config.php
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    networks:
      - backend

  ### PHP-FPM Container #######################################
  php-fpm:
    #image: laradocklite/php-fpm:latest
    build:
      context: ./php-fpm
    restart: unless-stopped
    volumes_from:
      - applications
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - "9000"
    depends_on:
      - php-worker
      - mysql
      - redis
      - elasticsearch
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend

  ### PHP Worker Container #####################################
  php-worker:
    #image: laradocklite/php-worker:latest
    build:
      context: ./php-worker
    restart: unless-stopped
    volumes_from:
      - applications
    volumes:
      - ./php-worker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - backend

  ### MySQL Container #########################################
  mysql:
    #image: laradocklite/mysql:latest
    build:
      context: ./mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  ### Redis Container #########################################
  redis:
    #image: laradocklite/redis:latest
    build:
      context: ./redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

  ### ElasticSearch Container #################################
  elasticsearch:
    #image: laradocklite/elasticsearch:latest
    build:
      context: ./elasticsearch
    restart: unless-stopped
    user: elasticsearch
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      - backend

  kibana:
    #image: laradocklite/kibana:latest
    build:
      context: ./kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - backend

### Networks Setup ############################################
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
